# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yinr's Site
# brief-intro: Yinr's Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yinr.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

# other links
twitter_username: HuYinr
# facebook_username:
github_username: Yinr
email: hssyinr@yeah.net
# weibo_username:
# zhihu_username:
# linkedIn_username:
# dribbble_username:

description_footer: Yinr 的个人站点~

# comments
# four ways to comment, only choose one, and use your own short name
# 四种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: yinr
disqus_shortname: yinrs
# youyan_shortname: 2125769
# laibili_shortname: MTAyMC8yODAxNS80NTky

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 2f315bef02035d2042f81c886ecd8677
cnzz_id: 1261297347 # 站长统计 id
google_analytics_id: UA-73941744-1 # google 分析追踪id

# 百度云观测代码
# 百度云观测 token
# <meta baidu-gxt-verify-token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
baidu_ce_token: 29465ccac1f5f7914c14768453dc4a1a

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n## "

# paginate
gems: [jekyll-paginate]
paginate: 10

# default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Yinr"
      # category: "none"
      tags: "none"
